enableVersioning: true
handle: aboutUs
name: About-us
propagationMethod: all
siteSettings:
  f331ccb8-ea07-4a40-96a1-2a7416f82a79: # Qualify test CRAFT
    enabledByDefault: true
    hasUrls: true
    template: about
    uriFormat: about
type: single
